👌 IMPROVE: nginx

diff --git a/bash/snippets/server-functions b/bash/snippets/server-functions
--- a/bash/snippets/server-functions
+++ b/bash/snippets/server-functions
@@ -51,17 +51,63 @@ stop_apache() {
   "$GITPOD_REPO_ROOT"/bash/utils.sh parse_ini_value starter.ini development apache_log_monitor)"
   case $log_monitor_type in
     'tail')
-    # The grep string here must match the tail portion of the command given in the function start_apache
+    # The grep string here must match the tail portion of the command given in the function tail_apache
     pid=$(ps axf  | grep 'tail -f /var/log/apache2/access.log /var/log/apache2/error.log' \
     | grep -v grep | awk '{print $1}' | sed 1q)
     ;;
     'multitail')
-    # The grep string here must match the command given in the function start_apache
+    # The grep string here must match the command given in the function mtail_apache
     pid=$(ps axf | grep 'multitail /var/log/apache2/access.log -I /var/log/apache2/error.log' \
     | grep -v grep | awk '{print $1}' | sed 1q)
     ;;
     *)
     echo "ERROR stop_apache: invalid apache_log_monitor type: $log_monitor_type. Check your starter.ini"
+    ;;
+  esac
+  [[ -n $pid ]] && kill -2 "$pid"
+}
+
+start_nginx() {
+  apachectl start
+  local exit_code=$?
+  (( exit_code == 0 )) || return
+  local log_monitor_type=
+  log_monitor_type="$(bash \
+  "$GITPOD_REPO_ROOT"/bash/utils.sh parse_ini_value starter.ini development apache_log_monitor)"
+  case $log_monitor_type in
+    'tail')
+    tail_apache
+    ;;
+    'multitail')
+    mtail_apache
+    ;;
+    *)
+    echo "ERROR start_nginx: invalid apache_log_monitor type: $log_monitor_type. Check your starter.ini"
+    ;;
+  esac
+}
+
+stop_nginx() {
+  apachectl stop
+  local exit_code=$?
+  (( exit_code == 0 )) || return
+  local pid
+  local log_monitor_type
+  log_monitor_type="$(bash \
+  "$GITPOD_REPO_ROOT"/bash/utils.sh parse_ini_value starter.ini development apache_log_monitor)"
+  case $log_monitor_type in
+    'tail')
+    # The grep string here must match the tail portion of the command given in the function tail_apache
+    pid=$(ps axf  | grep 'tail -f /var/log/nginx/access.log /var/log/nginx/error.log' \
+    | grep -v grep | awk '{print $1}' | sed 1q)
+    ;;
+    'multitail')
+    # The grep string here must match the command given in the function mtail_apache
+    pid=$(ps axf | grep 'multitail /var/log/nginx/access.log -I /var/log/nginx/error.log' \
+    | grep -v grep | awk '{print $1}' | sed 1q)
+    ;;
+    *)
+    echo "ERROR stop_enginx: invalid apache_log_monitor type: $log_monitor_type. Check your starter.ini"
     ;;
   esac
   [[ -n $pid ]] && kill -2 "$pid"
